apiVersion: apps/v1
kind: Deployment
metadata:
  name: myinsuranceappunax-deployment
  labels:
    app: myinsuranceapp-az
spec:
  replicas: 8
  selector:
    matchLabels:
      app: myinsuranceapp-az
  template:
    metadata:
      labels:
        app: myinsuranceapp-az
    spec:
      imagePullSecrets:
      - name: acr-secret-unax2
      containers:
      - name: myinsuranceapp-deployment-az
        image:  unaxmendizabal.azurecr.io/myinsuranceappunax:v8
        ports:
        - name: http
          containerPort: 5000