apiVersion: v1
kind: Service
metadata:
  name: myinsuranceappunax-service
  labels:
    app: myinsuranceapp-az
spec:
  type: NodePort
  selector:
    app: myinsuranceapp-az 
  ports:
  - port: 5050
    targetPort: http
    nodePort: 32420
    protocol: TCP    
    name: http